version: '3.8'

# Atlas Microservices - Local Development
# Run: docker-compose up --build
# This will start all services with proper dependencies and health checks

services:
  # Infrastructure services - start first
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atlas-network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d atlas"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atlas-network

  # Gateway service - starts after infrastructure
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DOCKER_ENV=true
    env_file:
      - ./services/gateway/.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=5", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - atlas-network

  # Microservices - start after gateway
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth/.env
    depends_on:
      gateway:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - atlas-network

  user-service:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./services/user/.env
    depends_on:
      gateway:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - atlas-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  atlas-network:
